### ISSUE TITLE
我在使用时遇到了一个问题!

### ISSUE THREAD

**Issue by XIAYM-gh** [yesvods/nocode#10]
当我尝试运行我刚修改完的代码时,发生了这样的问题:
`                                                         `
这是代码:
`                                                      
                                             
                                        `
这是修改之前的代码:
`                      `
为什么会出现这样的问题? 求各位大神赐教.

**Comment by truebigsand** [comment]
这是一个很典型的错误
它来自于你代码中的
```
```
修改前是不会发生这样的错误的
所以你可以不修改此处代码，或者改成这种形式
```
```
