### ISSUE TITLE
请教一下，在编程过程中，出现了这样的BUG

### ISSUE THREAD

**Issue by TennousuAthena** [yesvods/nocode#4]
初次使用面向佛系编程，请大家包涵！
这是运行的代码：
```
   
```
我觉得他的输出应该是
`  `
他却返回了
`    `
求各位大神赐教，谢谢！

**Comment by yesvods** [comment]
这是初学者容易遇到的常见问题，我们面向佛系编程时候，常记住默念：不写任何代码

这个问题只要通过这种方式，就迎刃而解：

```
```

想继续深入了解相关的问题，务必每天回顾一下[佛系编程指南](https://github.com/yesvods/nocode)
